dist: xenial 
language: python
python:
  - "3.7.3"
services:
  - docker

script:
  - cp .env.travis .env
  - sudo docker-compose -f ./docker-compose-stage.yml up -d
  - sudo docker-compose  exec  web python manage.py test .
  # - sudo docker-compose  exec  web python manage.py test functional_tests