dist: xenial 
language: python
python:
  - "3.7.3"
services:
  - docker

script:
  - cp .env.travis .env
  - sudo docker-compose build web
  - sudo docker-compose up -d
  - sudo docker-compose  exec  web python manage.py test .