dist: xenial 
language: python
python:
  - "3.7.3"
install:
  - pip install -r ./src/requirements.txt

script:
  - cd src
  - python manage.py makemigrations auth
  - python manage.py migrate --run-syncdb
  - python manage.py test .