version: '2'  
services:  
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web_container
    depends_on:
      - db
    volumes:
      - ./src:/src
    links:
      - redis
  db:
    image: postgres:alpine
    container_name: postgres_container
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
     - '6379:6379'
