# Generated by Django 2.2.2 on 2019-07-06 21:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='The number of the route if given e.g. route 6 or 11.')),
                ('grade', models.IntegerField(verbose_name='Grade of climbing route')),
                ('grade_sub', models.IntegerField(default=0, null=True, verbose_name='Optional sub grade of climbing route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_date', models.DateField(verbose_name='This is the date that the route set was available')),
                ('down_date', models.DateField(default=datetime.date(2000, 1, 1), null=True, verbose_name='This is the date that the route set was taken down')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('level', models.IntegerField(verbose_name='Climbing level')),
            ],
        ),
        migrations.CreateModel(
            name='RouteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='E.g. mastered, climbed, attempted, todo')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.RouteSet'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
