# Generated by Django 2.2.2 on 2019-07-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerecord',
            name='is_climbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Profile'),
        ),
    ]
