# Generated by Django 2.2.3 on 2019-07-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20190707_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingGym',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('gym_key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
