# Generated by Django 2.2.3 on 2019-07-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_climbinggym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('email', models.EmailField(default='edinburgh@edenrockclimbing,com', max_length=254)),
                ('gym_key', models.CharField(default='eden_edi', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Eden Rock Edinburgh', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='ClimbingGym',
        ),
    ]
