# Generated by Django 2.2.3 on 2019-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20190712_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gym_key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
