# Generated by Django 2.2.3 on 2019-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerecord',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
