# Generated by Django 2.2.6 on 2019-10-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerecord',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date of completed climb'),
        ),
    ]
