# Generated by Django 2.2.6 on 2019-11-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20191016_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routerecord',
            old_name='status',
            new_name='record_type',
        ),
        migrations.RemoveField(
            model_name='routerecord',
            name='is_climbed',
        ),
    ]
