# Generated by Django 2.2.7 on 2020-01-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20191105_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='gym',
            name='website',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='routeset',
            name='zone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
