# Generated by Django 2.2.8 on 2020-01-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20200108_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Gym')),
            ],
        ),
    ]
